name: Automated Testing CI/CD

on:
  push:
    branches: ["main", "master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge] # Tuyệt chiêu chẻ đôi luồng chạy ở dòng này
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
